//
//  UIColor+Easyintest.swift
//
//  Generated by Zeplin on 3/16/17.
//  Copyright (c) 2017 __MyCompanyName__. All rights reserved. 
//

import UIKit

extension UIColor {
	class var easyOrangeRed: UIColor {
		return UIColor(red: 255.0 / 255.0, green: 31.0 / 255.0, blue: 31.0 / 255.0, alpha: 1.0)
	}

	class var easyGreyish: UIColor { 
		return UIColor(white: 172.0 / 255.0, alpha: 1.0)
	}

	class var easyAlmostWhite: UIColor {
		return UIColor(red: 239.0 / 255.0, green: 238.0 / 255.0, blue: 237.0 / 255.0, alpha: 1.0)
	}

	class var easyGrass: UIColor {
		return UIColor(red: 101.0 / 255.0, green: 190.0 / 255.0, blue: 48.0 / 255.0, alpha: 1.0)
	}

	class var easyDarkSkyBlue: UIColor {
		return UIColor(red: 77.0 / 255.0, green: 146.0 / 255.0, blue: 227.0 / 255.0, alpha: 1.0)
	}

	class var easyWarmGrey: UIColor { 
		return UIColor(white: 151.0 / 255.0, alpha: 1.0)
	}

	class var easyAlmostBlack: UIColor { 
		return UIColor(white: 51.0 / 255.0, alpha: 1.0)
	}

	class var easyGraph1: UIColor {
		return UIColor(red: 77.0 / 255.0, green: 66.0 / 255.0, blue: 137.0 / 255.0, alpha: 1.0)
	}

	class var easyGraph2: UIColor {
		return UIColor(red: 0.0, green: 200.0 / 255.0, blue: 179.0 / 255.0, alpha: 1.0)
	}

	class var easyDarkSkyBlueTwo: UIColor {
		return UIColor(red: 73.0 / 255.0, green: 144.0 / 255.0, blue: 226.0 / 255.0, alpha: 1.0)
	}

	class var easySoftBlue: UIColor {
		return UIColor(red: 109.0 / 255.0, green: 161.0 / 255.0, blue: 223.0 / 255.0, alpha: 1.0)
	}
}
